language: node_js

node_js:
    - "node"
    #- "7"
    #- "6"
    #- "5"
    #- "4"
    #- "iojs"
    #- "4.1"
    #- "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:
    - make install



script:
    - make test



notifications:
    webhooks:
        urls:
            # desinax/dev
            - https://webhooks.gitter.im/e/cfe9d5af114f67125ae2

            # desinax/css-stylesheet
            - https://webhooks.gitter.im/e/4bd7c8ff7244fea3a6e5

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
